/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FilterSidebar: typeof import('./src/components/icons/FilterSidebar.vue')['default']
    Sidebar: typeof import('./src/components/icons/Sidebar.vue')['default']
  }
}
