/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FilterSearch: typeof import('./src/components/FilterSearch.vue')['default']
    FilterSidebar: typeof import('./src/components/FilterSidebar.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    PopUp: typeof import('./src/components/PopUp.vue')['default']
    Sidebar: typeof import('./src/components/icons/Sidebar.vue')['default']
  }
}
