name: Publish artifact to Github

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and upload application
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install

      - name: Build with Vite
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist
